### ISSUE TITLE
how to execute the migration_runner?

### ISSUE THREAD

**Issue by cindRoberta** [dukefirehawk/angel#10]

**Comment by cindRoberta** [comment]
https://github.com/dukefirehawk/angel/blob/angel3/packages/orm/angel_migration_runner/example/main.dart

**Comment by atreeon** [comment]
thanks @cindRoberta, out of interest what do you use now and why did you stop using Dart as a backend?

**Comment by cindRoberta** [comment]
> thanks @cindRoberta, out of interest what do you use now and why did you stop using Dart as a backend?

I started using Actix and Axum with the ORMs Sea-orm and Diesel, all from Rust

But I think that any mainstream framework today is better than Dart, shelf is excelent, but other Dart backend frameworks are still in the development stage

Phoenix (Elixir)
Spring (Java)
Django or other (Python)

**Comment by atreeon** [comment]
I really like the Dart syntax but I the sql ORM just isn't there for Dart.  Yup, Shelf is really good and Alfred too, supabase has good support in Dart actually but it doesn't have a strongly typed ORM.  It could be easy to build one but I don't have the time.  Historically I'm used to c#'s entity framework and I don't think I realised just how grateful I should have been; it seems more intuitive than anything else I've seen.  I think I'm going to return to c# & .net for my backend stuff as I already know it and you can builder a docker container with it now too; I will be locked into Azure Sql but I think it is worth it.  Flutter & Dart will continue to be my first choice for the front end.

**Comment by cindRoberta** [comment]
> I really like the Dart syntax but I the sql ORM just isn't there for Dart.  Yup, Shelf is really good and Alfred too, supabase has good support in Dart actually but it doesn't have a strongly typed ORM.  It could be easy to build one but I don't have the time.  Historically I'm used to c#'s entity framework and I don't think I realised just how grateful I should have been; it seems more intuitive than anything else I've seen.  I think I'm going to return to c# & .net for my backend stuff as I already know it and you can builder a docker container with it now too; I will be locked into Azure Sql but I think it is worth it.  Flutter & Dart will continue to be my first choice for the front end.

try webAssembly too
