### ISSUE TITLE
What is the purpose of the `error` field in angel3_model?

### ISSUE THREAD

**Issue by debuggerx01** [dukefirehawk/angel#21]
Hi, @dukefirehawk 

I wonder know what is the purpose of the `error` field in this line:

https://github.com/dukefirehawk/angel/blob/e8af46492cc8907292cbe91966b63fbfe74f750b/packages/model/lib/angel3_model.dart#L8

It seems useless on my database table.

**Comment by dukefirehawk** [comment]
@debuggerx01 `error` is no longer being used. It was added to test the ORM code generator. Will publish an updated `angel3_model`.

**Comment by debuggerx01** [comment]
> `error`不再使用@debuggerx01。添加它是为了测试 ORM 代码生成器。将发布更新的`angel3_model`.

Thx~
