### ISSUE TITLE
suggestion : rename the framework

### ISSUE THREAD

**Issue by mostafaElspagh0** [dukefirehawk/angel#3]
I can't find the framework by searching for it on google and the old archived version make things worse and I think this version is in active development so why not renaming it

**Comment by dukefirehawk** [comment]
All the active development work up to this point is to get "angel" framework to support NNBD and publish them with "angel3_" prefix without making drastic changes to all the packages that uses "angel" name in the code.  In essence, what used to work in the old version can be migrated to "angel3" without making too much changes. Now that all the key packages are in NNBD, we would like to stabilize them first before making a name change which would trigger a major rework on not only the packages but also examples, tutorials, user guide etc. The website is currently under rebuilding from scratch. Once done, it should be able to provide the consolidated information at one location, https://angel3-framework.web.app.

**Comment by dukefirehawk** [comment]
The revamped website is up at https://angel3-framework.web.app

**Comment by insinfo** [comment]
@dukefirehawk
great job congratulations

**Comment by mjablecnik** [comment]
@dukefirehawk Why you didn't ask of thosakve (original author of Angel) if he can change the rights and repository for you?
This can be good for prevent renaming of this framework..

**Comment by dukefirehawk** [comment]
@mjablecnik We did discuss about it and it was my decision not to proceed after looking at the source code, documentation etc. Taking over mean that I have to take on support and maintain immediately which I wasn't ready as there are 70++ over packages to migrate. So, it is better for it to be retired first. It took 4++ months to get them all to null safety. So I published them as Angel3, a cleaner breakaway, but retain some reference to the old version.

**Comment by insinfo** [comment]
@dukefirehawk
I forked Angel a few months ago and updated some packages to work with dart 2.12 and renamed it to Galileo, and published those packages as galileo_, I'm even using that fork in production on some projects, but I haven't had much time to convert all packages to null security, if you are interested in a new name for the project I will be happy if you choose the Galileo name and if you want I can donate the domain https://galileodart.com/ and the hosting

**Comment by dukefirehawk** [comment]
@insinfo Thanks for the offer. Changing name is not on the card as it involves a lot of work for very little gain. Now that the entire framework has been ported to null safety, there are a number of areas that I would rather spend time on i,e, ORM for MySQL, TechEmpower Framework Benchmarks, improving examples etc.
