### ISSUE TITLE
orm: createdAt and updatedAt fields are null by default?

### ISSUE THREAD

**Issue by outersky** [dukefirehawk/angel#53]
Maybe these two fields should be set automatically , or is there a plugin to handle this ?

**Comment by debuggerx01** [comment]
Hi, these two fields can be set automatically after this pr: 
[https://github.com/dukefirehawk/angel/pull/22](https://github.com/dukefirehawk/angel/pull/22) 
You can see the link above and check where the version of ` angel_orm` is 4.0.2 or above, if any questions , please feel free to contact me and provide a simple demo if convenient.

**Comment by dukefirehawk** [comment]
@outersky Are you still facing this issue?

**Comment by outersky** [comment]
> @outersky Are you still facing this issue?

@dukefirehawk  I managed to make it work finally , with an explicit null assignment to that date field, but it seems that the timezone info is lost, and it uses web server's time instead of database server's current_timestamp().

 PS: I'm trying to create another simple orm framework for dart : [needle_orm_generator](https://github.com/outersky/needle_orm_generator.dart)

**Comment by dukefirehawk** [comment]
@outersky Thanks for the feedback. Your ORM project looks great. Will be watching it. One of my goal is to evolve `angel3_orm` in the direction of Spring data JPA / Hibernate.

**Comment by outersky** [comment]
@dukefirehawk I make the prototype run finally, all advice is welcome :) 

 [needle_orm_example project](https://github.com/needle-dart/needle_orm_example)

**Comment by dukefirehawk** [comment]
PostgreSQL driver converts and stores datetime in UTC by default. `Column` annotation has been expanded to support default value for timestamp field, i.e. @Column(defaultValue: 'now()')
