### ISSUE TITLE
TODOs starting app serialization error

### ISSUE THREAD

**Issue by tomwyr** [dukefirehawk/angel#56]
After creating new GraphQL project using Angel CLI, any query/mutation requesting `Date` fields in its response fails.
```
{
  todos {
    id
    created_at
  }
}
```
Returns:
```
{
  "errors": [
    {
      "message": "Value of field \"created_at\" must be DateTime, got 2022-03-05T11:00:15.665164 (String) instead."
    }
  ]
}
```

**Comment by tomwyr** [comment]
I'm fairly new to Angel and GraphQL but it looks like `MapService` stores timestamps as `String` but then GQL `Date` type attempts to serialize them as if they were `DateTime`:
https://github.com/dukefirehawk/graphql_dart/blob/master/graphql_server/lib/graphql_server2.dart#L564
https://github.com/dukefirehawk/graphql_dart/blob/master/graphql_schema/lib/src/scalar.dart#L133

**Comment by dukefirehawk** [comment]
We will get this resolved. Thanks for reporting it.
