### ISSUE TITLE
Typo in docs: angel_cli => angel3_cli

### ISSUE THREAD

**Issue by NeroSong** [dukefirehawk/angel#58]
the following install command in the [doc](https://angel3-docs.dukefirehawk.com/guides/cli-setup) will fail in Windows:

`$ pub global activate angel_cli`

then I find it's `angel3_cli` in Github README, and it works fine.

Hope it can be updated to help more beginners, thx :)

**Comment by NeroSong** [comment]
and all `angel` => `angel3`

**Comment by dukefirehawk** [comment]
We will get the documentation updated

**Comment by dukefirehawk** [comment]
[Angel3 Guide](https://angel3-docs.dukefirehawk.com/guides/cli-setup) has been updated
