### ISSUE TITLE
Null-safe at Getting started

### ISSUE THREAD

**Issue by devnullsp** [dukefirehawk/angel#59]
I found problems with documentation samples:
At Getting started:

var name = req.bodyAsMap['name'] as String;
if (name == null) {

Give on error about null isnt a String.....

I changed by:

String? name = req.bodyAsMap['name'];
if (name == null) {

Sorry i writed at chat but no response....
TIA.

**Comment by dukefirehawk** [comment]
The document is a bit outdated after the migration to null-safety and some of the latest ongoing work. We will be revising the document soon for version 6.0.0. is stable. In the meantime, if you find anything that is not working as expected, this a good place to raise it as we track the progress. The discussion forum is fine too.

**Comment by dukefirehawk** [comment]
[Angel3 Guide - Getting Started](https://angel3-docs.dukefirehawk.com/guides/getting-started) has been updated.

**Comment by dukefirehawk** [comment]
Updated and moved `Getting Started` to tutorial section at  https://angel3-docs.dukefirehawk.com/tutorial/getting-started
